name: jiedaitong
version: 1

libraries:
- name: "django"
  version: "1.5"

handlers:
- url: /static
  static_dir: static

cron:
- description: "每天凌晨0点自动更新当天需要付息的记录"
  url: /admin/record/repay/update
  schedule: "0 0 * * *"