name: jiedaitong
version: 1

libraries:
- name: "django"
  version: "1.5"

handlers:
- url: /static
  static_dir: static

cron:
- description: repay_record_autp_update
  url: /admin/record/repay/update
  schedule: "*/1 * * * *"